import { chromium } from 'playwright';
import fs from 'node:fs';
const ep='/opt/pw-browsers/chromium';
const OUT='/tmp/claude-0/-home-user-portfolio/42453b4b-19a6-5e13-bfbe-237400d76d6d/scratchpad/shots';
const route=process.argv[2]||'/experience';
const name=process.argv[3]||'experience';
const b=await chromium.launch({executablePath:fs.existsSync(ep)?ep:undefined});
const c=await b.newContext({viewport:{width:1440,height:900}}); const p=await c.newPage();
await p.goto('http://localhost:4173'+route,{waitUntil:'networkidle'}).catch(()=>{});
await new Promise(r=>setTimeout(r,2500));
await p.screenshot({path:`${OUT}/${name}-desktop.png`});
await b.close(); console.log('shot '+name);
